### ISSUE TITLE
[consultas-multiplas-tabelas] Trabalhando com LEFT JOIN

### ISSUE THREAD

**Issue by Kamilahsantos** [WoMakersCode/banco-de-dados#33]
to-do : detalhar left join

**Comment by suzukikarol** [comment]
Adicionado um arquivo que falo um pouco sobre o que é JOIN.
PR aberta pra pra análise.
link : https://github.com/WoMakersCode/banco-de-dados/pull/42

**Comment by Kamilahsantos** [comment]
closed by #42
